/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhonghong_jni_JniClient */

#ifndef _Included_com_zhonghong_jni_JniClient
#define _Included_com_zhonghong_jni_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    looper
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhonghong_jni_JniClient_looper
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    HelloBlueTooth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhonghong_jni_JniClient_HelloBlueTooth
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    GetBlueToothVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhonghong_jni_JniClient_GetBlueToothVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    getStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhonghong_jni_JniClient_getStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    getKeyStat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhonghong_jni_JniClient_getKeyStat
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    getLEDStat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhonghong_jni_JniClient_getLEDStat
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    getIOStat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhonghong_jni_JniClient_getIOStat
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhonghong_jni_JniClient_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_zhonghong_jni_JniClient
 * Method:    postCmd
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhonghong_jni_JniClient_postCmd
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
